try {
    throw Exception("Test");
    out("c-0");
} catch (_) {
    out("c-1");
}
